bottle:
  test:
    messages:
    - The quick brown fox jumps over the lazy dog.
    - I am so blue I'm greener than purple.
    - I stepped on a Corn Flake, now I'm a Cereal Killer
    - On a scale from one to ten what is your favourite colour of the alphabet.
    - Look, a distraction!
    - I'm a lumberjack and I'm ok, I drink all night and I toke all day
    - Natural selection is anything but random.
    - What's my age again?
    - Life is like stepping onto a boat which is about to sail out to sea and sink
    - Never mistake a clear view for a short distance
    - Do not go gentle into that long, dark night but rage, rage against the dying of the light.